global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheusJob'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090'] #Servidor prometheus
  - job_name: 'spring-monitoring-demo'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.0.101:8080'] #Servidor da minha aplicação